networks:
  localdev:
    name: localdev

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    networks:
      - localdev
    volumes:
      - ./server:/app
      - ./server/node_modules:/app/node_modules
    depends_on:
      - client

  client:
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - localdev
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules
