@base = http://localhost:5000

POST {{base}}/get-longest-word
Accept: application/json
Content-Type: application/json

{
    "text": "Some text with alongword"
}

###
POST {{base}}/get-longest-word
Accept: application/json
Content-Type: application/json

{
    "text": ""
}
